/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mobilex_piposerver_PiposerverApplication */

#ifndef _Included_com_mobilex_piposerver_PiposerverApplication
#define _Included_com_mobilex_piposerver_PiposerverApplication
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mobilex_piposerver_PiposerverApplication
 * Method:    helloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mobilex_piposerver_PiposerverApplication_ImportationTest
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
