/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mobilex_piposerver_service_PipoService */

#ifndef _Included_com_mobilex_piposerver_service_PipoService
#define _Included_com_mobilex_piposerver_service_PipoService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mobilex_piposerver_service_PipoService
 * Method:    processPipo
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mobilex_piposerver_service_PipoService_processPipo
  (JNIEnv *, jobject, jstring, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
